version: '3.0'

services:
  nginx:
    image: nginx:latest
    networks:
      - backend
      - frontend
    ports:
      - "6666:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www:/www
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
  php:
    image: php:fpm
    networks:
      - backend
    volumes:
      - ./www:/www
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
  mysql:
    image: mariadb:latest
    networks:
      backend:
        aliases:
          - db
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    deploy:
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - "node.role == manager"
  phpmyadmin:
    image: phpmyadmin:latest
    networks:
      - backend
      - frontend
    ports:
      - "6001:80"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any

networks:
  frontend:
  backend:

volumes:
  www:
